<?php

if($post_type=="image/jpeg"){$post_type="jpg";}
else if($post_type=="image/jpg"){$post_type="jpg";}
else if($post_type=="image/x-citrix-jpeg"){$post_type="jpg";}// appears only  if file post with attach id already generated by wordpress, other cases so far have not to be proved
else if($post_type=="image/x-citrix-png"){$post_type="png";}// appears only  if file post with attach id already generated by wordpress, other cases so far have not to be proved
else if($post_type=="image/x-citrix-gif"){$post_type="gif";}// appears only  if file post with attach id already generated by wordpress, other cases so far have not to be proved
else if($post_type=="image/png"){$post_type="png";}
else if($post_type=="image/gif"){$post_type="gif";}
//else if($post_type=="image/vnd.microsoft.icon"){$post_type="ico";}
//else if($post_type=="image/x-icon"){$post_type="ico";}
else if($post_type=="application/pdf" && !$cgProFalse){$post_type="pdf";$isAlternativeFile=true;}
else if($post_type=="application/zip" && !$cgProFalse){$post_type="zip";$isAlternativeFile=true;}
else if($post_type=="text/plain"){$post_type="txt";$isAlternativeFile=true;}
else if($post_type=="application/msword"){$post_type="doc";$isAlternativeFile=true;}
else if($post_type=="application/vnd.openxmlformats-officedocument.wordprocessingml.document"){$post_type="docx";}
else if($post_type=="application/vnd.ms-excel"){$post_type="xls";$isAlternativeFile=true;}
else if($post_type=="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"){$post_type="xlsx";}
else if($post_type=="text/csv"){$post_type="csv";$isAlternativeFile=true;}
else if($post_type=="audio/mpeg" && $fullFilePathEnd=='mp3' && !$cgProFalse){$post_type="mp3";$isAlternativeFile=true;}
else if($post_type=="audio/wav" && !$cgProFalse){$post_type="wav";$isAlternativeFile=true;}
else if($post_type=="audio/mpeg" && $fullFilePathEnd=='m4a'){$post_type="m4a";$isAlternativeFile=true;}
else if($post_type=="audio/ogg"){$post_type="ogg";$isAlternativeFile=true;}
else if($post_type=="video/mp4" && !$cgProFalse){$post_type="mp4";$isAlternativeFile=true;}
else if($post_type=="video/quicktime" && !$cgProFalse){$post_type="mov";$isAlternativeFile=true;}
else if($post_type=="video/webm"){$post_type="webm";$isAlternativeFile=true;}
else if($post_type=="application/vnd.ms-powerpoint" && $fullFilePathEnd=='ppt'){$post_type="ppt";$isAlternativeFile=true;}// no pps allowed! because ppsx are not alloed generally in media library upload
else if($post_type=="application/vnd.openxmlformats-officedocument.presentationml.presentation"){$post_type="pptx";$isAlternativeFile=true;}
else if($post_type=="contest-gallery-youtube"){$post_type="ytb";$isAlternativeFile=true;}
else if($post_type=="contest-gallery-twitter"){$post_type="twt";$isAlternativeFile=true;}
else if($post_type=="contest-gallery-instagram"){$post_type="inst";$isAlternativeFile=true;}
else if($post_type=="contest-gallery-tiktok"){$post_type="tkt";$isAlternativeFile=true;}
//else if($post_type=="video/x-ms-wmv" && !$cgProFalse){$post_type="wmv";$isAlternativeFile=true;}
//else if($post_type=="video/avi" && !$cgProFalse){$post_type="avi";$isAlternativeFile=true;}
else{
    $doNotProcess=1;
}

?>