<?php
if(!function_exists('cg_stripe_list_customers')){
    function cg_stripe_list_customers($email,$secret){

	    $params = [
		    'email' => $email,
	    ];

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	    $ch = curl_init();

	    curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/customers');
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_POST, 0);
	    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));
	    curl_setopt($ch, CURLOPT_USERPWD, $secret. ':' . '');

	    $headers = array();
	    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
	    $headers[] = 'limit: 1';
	    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	    $result = json_decode(curl_exec($ch),true);

	    if (curl_errno($ch)) {
		    echo 'Error cg_stripe_list_customers:' . curl_error($ch);
	    }else{
		    if(!empty($result['error']['message'])){
			    echo 'Error cg_stripe_list_customers:' . $result['error']['message'];
		    }
	    }

	    curl_close($ch);

	    $return = [];

	    if(!empty($result['data'][0])){
		    $return = $result['data'][0];
	    }

		return $return;

    }
}
